v2: linux: add lmbench memory test
Change-Id: I72b41173ce2ba2c1f685e41ea119d7f9372d2651
Signed-off-by: Chase Qi <chase.qi@linaro.org>

diff --git a/automated/lib/sh-test-lib b/automated/lib/sh-test-lib
--- a/automated/lib/sh-test-lib
+++ b/automated/lib/sh-test-lib
@@ -95,6 +95,15 @@ add_metric() {
     echo "${test} ${result} ${measurement} ${units}" | tee -a "${RESULT_FILE}"
 }
 
+detect_abi() {
+    abi=$(uname -m)
+    case "${abi}" in
+      armv7|armv7l|armv7el|armv7lh) abi="armeabi" ;;
+      arm64|armv8|arm64-v8a|aarch64) abi="arm64" ;;
+      *) error_msg "Unknown architecture: ${abi}" ;;
+    esac
+}
+
 dist_name() {
     if [ -x /usr/bin/lsb_release ]; then
         dist="$(lsb_release -si)"
@@ -128,12 +137,15 @@ install_deps() {
           Debian|Ubuntu)
             # Use the default answers for all questions.
             DEBIAN_FRONTEND=noninteractive apt-get update -q -y
+            # shellcheck disable=SC2086
             DEBIAN_FRONTEND=noninteractive apt-get install -q -y ${pkgs}
             ;;
           CentOS)
+            # shellcheck disable=SC2086
             yum -e 0 -y install ${pkgs}
             ;;
           Fedora)
+            # shellcheck disable=SC2086
             dnf -e 0 -y install ${pkgs}
             ;;
           Unknown)
@@ -141,6 +153,20 @@ install_deps() {
             ;;
         esac
     fi
+}
+
+# Return the exit code of the first command when using pipe.
+pipe0_status() {
+    [ "$#" -ne 2 ] && error_msg "Usage: pipe0_status cmd1 cmd2"
+    local cmd1="$1"
+    local cmd2="$2"
+
+    exec 4>&1
+    ret_val=$({ { eval "${cmd1}" 3>&-; echo "$?" 1>&3; } 4>&- \
+                | eval "${cmd2}" 1>&4; } 3>&1)
+    exec 4>&-
+
+    return "${ret_val}"
 }
 
 validate_check_sum() {
@@ -152,12 +178,31 @@ validate_check_sum() {
     OUTPUT_FILE_NAME="$1"
     SHA256SUM_CHECK="$2"
     # Get sha256sum of output_file
-    GET_SHA256SUM=$(sha256sum ${OUTPUT_FILE_NAME} | awk '{print $1}')
-    echo "GET_SHA256SUM is "${GET_SHA256SUM}""
+    GET_SHA256SUM=$(sha256sum "${OUTPUT_FILE_NAME}" | awk '{print $1}')
+    echo "GET_SHA256SUM is ${GET_SHA256SUM}"
     if [ "${SHA256SUM_CHECK}" = "${GET_SHA256SUM}" ] ; then
         return 0
     else
         echo "checksum did not match"
         return 1
     fi
+}
+
+convert_to_mb() {
+    [ "$#" -ne 2 ] && error_msg "Usage: convert_to_mb value units"
+    if ! echo "$1" | egrep -q "^[0-9.]+$"; then
+        error_msg "The first argument isn't a number"
+    fi
+    local value="$1"
+    local units="$2"
+
+    case "${units}" in
+      KB|kb) value=$(echo "${value}" | awk '{print $1/1024}') ;;
+      MB|mb) ;;
+      GB|gb) value=$(echo "${value}" | awk '{print $1*1024}') ;;
+      TB|tb) value=$(echo "${value}" | awk '{print $1*1024*1024}') ;;
+      *) error_msg "Unsupported units" ;;
+    esac
+
+    echo "${value}"
 }
