sync with upstream
Change-Id: I03a1c7680f6ae07945e728fa9533436640ed2ef3
Signed-off-by: Chase Qi <chase.qi@linaro.org>

diff --git a/automated/lib/sh-test-lib b/automated/lib/sh-test-lib
--- a/automated/lib/sh-test-lib
+++ b/automated/lib/sh-test-lib
@@ -70,6 +70,30 @@ check_return() {
     fi
 }
 
+# When shell argument "-e" set in test script, check_return and exit_on_fail
+# would NOT work. run_test_case should be used instead.
+run_test_case() {
+    [ "$#" -lt 2 ] && error_msg "Usage: run_test_case <test_command> <test_case_id> [skip_list]"
+    local test_command="$1"
+    local test_case_id="$2"
+    local skip_list="$3"
+
+    if eval "${test_command}"; then
+        echo "${test_case_id} pass" | tee -a "${RESULT_FILE}"
+    else
+        echo "${test_case_id} fail" | tee -a "${RESULT_FILE}"
+        # When skip_list isn't empty, skip the tests and exit.
+        if [ -n "${skip_list}" ]; then
+            for i in ${skip_list}; do
+                echo "$i skip" | tee -a "${RESULT_FILE}"
+            done
+            exit 0
+        fi
+    fi
+
+    return 0
+}
+
 report_pass() {
     [ "$#" -ne 1 ] && error_msg "Usage: report_pass test"
     local test="$1"
@@ -205,4 +229,63 @@ convert_to_mb() {
     esac
 
     echo "${value}"
+}
+
+dist_info() {
+    if ! command -v lsb_release > /dev/null; then
+        dist_name
+        case "${dist}" in
+          Debian|Ubuntu) install_deps "lsb-release" ;;
+          CentOS|Fedora) install_deps "redhat-lsb-core" ;;
+          *) error_msg "Unsupported distro: dist_info skipped"
+        esac
+    fi
+
+    # shellcheck disable=SC2034
+    Release=$(lsb_release -r | awk '{print $2}')
+    Codename=$(lsb_release -c | awk '{print $2}')
+}
+
+add_key() {
+    [ "$#" -ne 1 ] && error_msg "Usage: add_key url"
+    local url="$1"
+
+    dist_name
+    case "${dist}" in
+      Debian|Ubuntu) wget -O - "${url}" | apt-key add - ;;
+      CentOS|Fedora) infor_msg "add_key isn't needed on ${dist}" ;;
+      *) error_msg "Unsupported distro: add_key skipped"
+    esac
+}
+
+add_repo() {
+    [ "$#" -lt 1 ] && error_msg "Usage: add_repo <url> [backports]"
+    local url="$1"
+
+    dist_name
+    case "${dist}" in
+      # Detect Debian/Ubuntu codename and add repo automatically. The same url
+      # should work on all distributions supported by the repo.
+      Debian|Ubuntu)
+        dist_info
+        if [ -z "$2" ]; then
+            backports=""
+        elif [ "$2" = "backports" ]; then
+            backports="-backports"
+        else
+            echo "Usage: add_repo <url> [backports]"
+            error_msg "$2 is not a supported argument, should be 'backports'"
+        fi
+        echo "deb ${url} ${Codename}${backports} main" \
+            >> "/etc/apt/sources.list.d/3rd-party-repo.list"
+        ;;
+      # It is not easy to amend url with distro version as its format may vary
+      # by repo. Test definition/plan should provide a correct repo url.
+      CentOS|Fedora)
+        wget -O - "${url}" >> "/etc/yum.repos.d/3rd-party.repo"
+        ;;
+      *)
+        error_msg "Unsupported distro: add_repo skipped"
+        ;;
+   esac
 }
